### ISSUE TITLE
Shotgun menu icon not showing

### ISSUE THREAD

**Issue by samkenw** [diegogarciahuerta/tk-substancepainter#1]
Hi Diego,

I have been trying ton install your engine but it is not showing in substance and I am not recieving an error in the shotgun console... Do yoiu know how I might debug this?

Thanks!

Greetings
Sam

**Comment by aiblis** [comment]
Do you have git installed on your system?
[https://git-scm.com/download/win](url)

You might find a warning that it's skipping the entire module as it cannot resolve the git argument. 

Also there's a mistake on the documentation. You should try adding to the engine_locations.yml this code instead 

`engines.tk-substancepainter.location:
  type: git
  path: https://github.com/diegogarciahuerta/tk-substancepainter
  version: v1.1.0
`

**Comment by sciibus** [comment]
Yes, git is installed. Thanks, I will try this!

**Comment by sciibus** [comment]
Hi, thanks, now the substance-plugin is being loaded into the plugins folder but I am getting the following error:

[Plugin - resources-updater] No project open, resources updater discarded
[Plugin - shotgun_bridge] (DEBUG) Shotgun engine | Initializing Shotgun Bridge Plugin.
[Plugin - shotgun_bridge] (DEBUG) Shotgun engine | Engine port:56273
[Plugin - shotgun_bridge] (DEBUG) Shotgun engine | Starting tk-substancepainter engine with params: "C:/Program Files/Shotgun/Python/python.exe" "Z:/Shotgun/ZwischenMehlUndMilch/install/git/tk-substancepainter/v1.1.0/startup/bootstrap.py"
[Plugin - shotgun_bridge] Shotgun engine | Shotgun Substance Painter Engine connection was lost. Restarting engine...

Do you know what this could be due to?

**Comment by aiblis** [comment]
Check this [other thread](https://github.com/diegogarciahuerta/tk-substancepainter/issues/2) as I also ran into the same issue and got it fixed by adding the unrealqt framework. 🖖

**Comment by sciibus** [comment]
Perfekt, that has done it! Many Thanks to you Sir!
I am now getting template errors on new file creation but I suppose that is of my own doing.

**Comment by aiblis** [comment]
Glad to hear that! 
Hope you can fix the rest :)

**Comment by changsJC** [comment]
Hi Diego, 
I am having similar problem getting this to work on mac. There is no errors on the shotgun launcher side, but on substance side I got similar error messages.

`[Plugin - shotgun_bridge] (DEBUG) Shotgun engine | Initializing Shotgun Bridge Plugin.
[Plugin - shotgun_bridge] (DEBUG) Shotgun engine | Engine port:50328
[Plugin - shotgun_bridge] (DEBUG) Shotgun engine | Starting tk-substancepainter engine with params: "/Applications/Shotgun.app/Contents/Resources/Python/bin/python" "/Users/username/Library/Caches/Shotgun/bundle_cache/git/tk-substancepainter/v1.1.1/startup/bootstrap.py"
[Plugin - shotgun_bridge] Shotgun engine | Shotgun Substance Painter Engine connection was lost. Restarting engine...`

I tried substance version 2018.3, 2019.1 and 2019.2, with or without unrealqt or not. The plugin is created on in Documents. Do you know what else might went wrong? Thank you!

**Comment by diegogarciahuerta** [comment]
Hi @changsJC , 
https://github.com/ue4plugins/tk-framework-unrealqt does not include PySide2 for Mac , so I'm afraid it won't work for that platform as it is.

**Comment by donalm** [comment]
Substance Painter noob Pipe TD here...

I'm getting this error:
```
[Plugin - shotgun_bridge] (DEBUG) Shotgun engine | Initializing Shotgun Bridge Plugin.
[Plugin - shotgun_bridge] (DEBUG) Shotgun engine | Engine port:57111
[Plugin - shotgun_bridge] (DEBUG) Shotgun engine | Starting tk-substancepainter engine with params: [Plugin - shotgun_bridge] Shotgun engine | Shotgun Substance Painter Engine connection was lost. Restarting engine...
```
I definitely have the Unreal QT Framework installed, and it's definitely getting loaded by Painter on startup.

I'm on Windows 10 pro, running Painter 2019.2.2 and I specified version 1.2.1 of tk-substancepainter in engine_locations.yml

I ran "tank cache_apps" from a Linux client, but I'm not trying to run the plugin on Linux.

BTW - I'm not sure what I should see on success - should there be an additional menu or menu entry in the UI? Or just the file open/close etc get redirected to the Shotgun asset browser?

BTW2 - I'm curious about the architecture - what is using websockets to talk to what? Does the Shotgun UI element run in a separate process or is the websocket connection to Shotgun Desktop?

I'd appreciate any suggestions :)

Thanks.

**Comment by diegogarciahuerta** [comment]
Hi Dónal.

If everything was to work as expected, you should see something like this:
[image: image.png]

A new shotgun icon in the toolbar (SG) should show up, where you can open
the shotgun menu. Please check all the apps that are supported in the github
account,
<https://github.com/diegogarciahuerta/tk-substancepainter/blob/master/README.md>but
basically all the common ones from any other engine,
loading/saving/publishing/etc...

Now if this does not work, there are a few things you can check,

- When you mention that you have the "Unreal QT Framework installed" , I
take you mean the tk-framework-unrealqt
<https://github.com/ue4plugins/tk-framework-unrealqt> , note that this
framework only works in windows. You can check it was downloaded correctly
in this location:
<wherever your pipeline configuration
is>/install\gitbranch\tk-framework-unrealqt.git\<commit-id>
I would check just in case tank cache_apps did not do the work, but from
what you are saying it seems it is loading it fine.

- I would take a look at the logs from shotgun, located here:

*C:\Users\<username>AppData\Roaming\Shotgun*
specifically, *tk-substancepainter.log,* and *tk-desktop.log*, it will give
you an indication what is going on. Can you see any errors there ?

- Another possibility is that you have a very restricted setup that block
some ports. (explain below)

The reason why I use websockets is that shotgun toolkit is written in
python and at the time you could only write plugins for substance painter
in QML. So the shotgun toolkit part is written in python, and anything
related to the operations within substance painter is written in QML. The
communication happens through websockets, more specifically between the
QtWebSockets implemented in QML, and the QtWebSockets implemented in the
PySide2 version I use from the tk-framework-unrealqt . For example, the
engine in python might request through websockets to QML to give back the
name of the project is loaded, so the engine can react to that and change
it's context accordingly, or any other operations like saving, exporting
textures , etc...

Because this communication back and forth is done through a socket/port, I
wonder if there is anything that is not allowing the QML bit to communicate
back to python. Next time you run it, I'd check the port number (printed in
the substance painter log) to see if for any reason is blocked.

The good news is that as of 2020.1, substance painter supports python3, but
the API is still in it's infancy and while I have a prototype of the engine
that supports it, it is no near close to the capabilities the QML API
supports. It seems they are actively working on this, so I'm hoping soon I
can just release a version that does not require the external framework,
which also in return will mean the engine works without any other issues in
Mac/Linux.

Hope this helps,

- Diego



_____________________________________________

[ D i e g o   G a r c i a   H u e r t a ]

*P i p e l i n e   &   P r o d u c t i o n   t o o l s   d e v e l o p m e
n t   *|  * A R  /  MR  /  V R   *
*E: diegogh2000@gmail.com <diegogh2000@gmail.com>*

**Comment by diegogarciahuerta** [comment]
For reference someone named Dónal must have posted a comment but then deleted it, I replied to his comment from a github email, not from this page.

I will close the issue until we find a tk framework that provides PySide2 in Mac/linux, as it is required for websockets to work.
